### PR TITLE
Refactor and Updates

### PR DESCRIPTION
**Pull request by trevor-vaughan**
* Add checks for minimum number of characters in a row from character
  sets
* Add an RPM spec file with build instructions in the README
* Add Tests
* Ensure that the config file is read the fewest number of times
  possible

### CODE REVIEW

**Comment by davidcoutadeur** [comment]
Hi Trevor,
Did you give a try to ppm: https://github.com/davidcoutadeur/ppm ?
ppm is a rewritting to check-password: it corrects some architecture drawbacks and add some nice new features.

**Comment by trevor-vaughan** [comment]
@davidcoutadeur No, I haven't. Basically, I did this a LONG time ago (hence the Changelog entry) and can now PR it since you're on GitHub.

Oh, I also tied this into cracklib on the back end.

If nothing else, maybe some of the ideas will be useful in the future.

**Comment by davidcoutadeur** [comment]
Ok, thank you for your help, it is always a pleasure to have feedbacks and contributions!
I don't know if it is to be merged, but I think a lot of ideas are great: tests, limiting reading the config file, keeping cracklib.
RPM is also interesting, but we also have a global "overlay openldap LTB package" for this.

**Comment by coudot** [comment]
@trevor-vaughan thanks for the patch
@davidcoutadeur As you know a little more the C code of this module, I let you decide to merge or not this patch

**Comment by davidcoutadeur** [comment]
Hi @trevor-vaughan,

I have given a look to your pull request, but I think there are some points preventing the merge, or at least some clarification I need:

> - Ensure the the configuration file is only read once per run,

1. Indeed, the code is improved because, before, the read_config_file was called for each config parameter (6 times)... But now the configuration file is not read once per run. It is read once per password modification, do you agree ?

2. In the meantime, I think your implementation as a flaw: if the configuration parameters are not passed in the exact order of the default "configuration structure" (see config_entries), this will lead to overwritting default values. Idem if a parameter is written two times for example. Could you reproduce / confirm the flow ?

> - Add maxConsecutivePerClass,

untested, but sounds interresting. Maybe a "0" default value would be less restrictive and thus better.

> - Add LDEBUG flag for local debugging,

The idea is interesting, but I don't know if there is some danger of using printf inside OpenLDAP code. Moreover, the code is duplicated: code included in "defined(DEBUG)" + code included in "defined(LDEBUG)".
And as some OpenLDAP people have suggested me, dynamic affectation is not advised, because it slows everything. (you are allocating debug messages) Maybe there is a way to avoid that?

> - Add test code and update Makefile.

I haven't tested yet, but this is a good idea.

>  pkg/ppolicy-check-password.spec 

There is already a spec file provided. And also a Debian packaging.
We could merge the modification in these official packages, and avoid suggesting people to recompile, don't you think ?

At this point, the merge can't be done.
1. If you make corrections in a new commit, we could reconsider,
2. else, and if you agree, we could just pick some ideas and integrate them. (your name can be quoted)

**Comment by davidcoutadeur** [comment]
Another point:

> Add test code and update Makefile.

In fact, I thought the test code could avoid recompilation.
For example, if the test binary could take the configuration parameters from conf file or command line, we could also allow the user to run his own tests, don't you think?
The internal tests could be written in bash, in the makefile (make test), for making sure there is no regression, by reading the cpass status code.

**Comment by davidcoutadeur** [comment]
For information, I have taken inspiration from your work to implement:
- maxConsecutivePerClass
- unit tests
in the ppm project.
https://github.com/davidcoutadeur/ppm/releases/tag/v1.5
The test program can also be used easily by LDAP administrators wanting to check the policy.

Integrating this work in openldap-ppolicy-check-password would require too much time for me. (fix check-password flaws + your pull request flaws)... And in my opinion, the ppm module should be the logical replacement for check-password: it fixes anything that goes wrong in check-password and adds a lot of features (the only missing feature is cracklib)

**Pull request closed without merging**
